[project]
name = "you-shu-ju"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiomysql>=0.3.2",
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "uvicorn>=0.54.0",
]
